package com.mycompany.projetodadosclimaticos.view;

import javax.swing.JLabel;


public class UltimaAtualizacaoTempo extends javax.swing.JInternalFrame {

    /**
     * Creates new form UltimaAtualizacaoTempo
     */
    public UltimaAtualizacaoTempo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLbTempValue = new javax.swing.JLabel();
        jLbUmiValue = new javax.swing.JLabel();
        jLbPreesaoValue = new javax.swing.JLabel();
        jLbData = new javax.swing.JLabel();

        jLabel1.setText("Temperatura");

        jLabel2.setText("Umidade");

        jLabel3.setText("Pressão");

        jLabel4.setText("Data");

        jLabel5.setText("Última atualização do tempo");

        jLbTempValue.setText("jLabel6");

        jLbUmiValue.setText("jLabel7");

        jLbPreesaoValue.setText("jLabel8");

        jLbData.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbTempValue)
                            .addComponent(jLbUmiValue)
                            .addComponent(jLbPreesaoValue)
                            .addComponent(jLbData))
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLbTempValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLbUmiValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLbPreesaoValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLbData))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbData;
    private javax.swing.JLabel jLbPreesaoValue;
    private javax.swing.JLabel jLbTempValue;
    private javax.swing.JLabel jLbUmiValue;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLbData() {
        return jLbData;
    }

    public void setjLbData(JLabel jLbData) {
        this.jLbData = jLbData;
    }

    public JLabel getjLbPreesaoValue() {
        return jLbPreesaoValue;
    }

    public void setjLbPreesaoValue(JLabel jLbPreesaoValue) {
        this.jLbPreesaoValue = jLbPreesaoValue;
    }

    public JLabel getjLbTempValue() {
        return jLbTempValue;
    }

    public void setjLbTempValue(JLabel jLbTempValue) {
        this.jLbTempValue = jLbTempValue;
    }

    public JLabel getjLbUmiValue() {
        return jLbUmiValue;
    }

    public void setjLbUmiValue(JLabel jLbUmiValue) {
        this.jLbUmiValue = jLbUmiValue;
    }






}
