/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.dadosclimaticos.view;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author itix
 */
public class CadastroDadosClimaticosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrincipalFame
     */
    public CadastroDadosClimaticosView() {
        initComponents();
        setLocation(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextTemperatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JtxtUmidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPressao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtData = new javax.swing.JFormattedTextField();
        jbSalva = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel1.setText("Cadastros  de dados climaticos");

        jLabel2.setText("Temperatura");

        jLabel3.setText("Umidade");

        jLabel4.setText("Pressão");

        jTextPressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPressaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Data");

        try {
            jtxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDataActionPerformed(evt);
            }
        });

        jbSalva.setText("Salvar");
        jbSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtxtUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2)
                                .addComponent(jTextTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtData, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPressao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSalva)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtxtUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jbSalva)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPressaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPressaoActionPerformed

    private void jtxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDataActionPerformed

    private void jbSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtUmidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextPressao;
    private javax.swing.JTextField jTextTemperatura;
    private javax.swing.JButton jbSalva;
    private javax.swing.JFormattedTextField jtxtData;
    // End of variables declaration//GEN-END:variables

    public JTextField getJtxtUmidade() {
        return JtxtUmidade;
    }

    public void setJtxtUmidade(JTextField JtxtUmidade) {
        this.JtxtUmidade = JtxtUmidade;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextPressao() {
        return jTextPressao;
    }

    public void setjTextPressao(JTextField jTextPressao) {
        this.jTextPressao = jTextPressao;
    }

    public JTextField getjTextTemperatura() {
        return jTextTemperatura;
    }

    public void setjTextTemperatura(JTextField jTextTemperatura) {
        this.jTextTemperatura = jTextTemperatura;
    }

    public JFormattedTextField getJtxtData() {
        return jtxtData;
    }

    public void setJtxtData(JFormattedTextField jtxtData) {
        this.jtxtData = jtxtData;
    }

    public JButton getJbSalva() {
        return jbSalva;
    }

    public void setJbSalva(JButton jbSalva) {
        this.jbSalva = jbSalva;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }


}
